spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${GITHUB_REDIRECT_URI}
            scope:
              - repo
              - user
environments:
  url:
    homeurl: ${HOME_URL}
  key:
    secretKey: ${JWT_SECRET_KEY}
